### ISSUE TITLE
Different Laundry lLists

### ISSUE THREAD

**Issue by franqfzh** [comp426-2022-spring/a02-franqfzh#1]
The coin.mjs file in a02 wants us to do countFlips and flipACoin but a02 assignment page wants us to do guess a flip instead. I wonder which instruction should I follow?

**Comment by camsimba** [comment]
Just making sure, you had this solved for you in the other issue right? If not, let me know!

**Comment by franqfzh** [comment]
Yeah this is solved. Thank you for asking.

**Comment by camsimba** [comment]
Perfect, I'll close this thread then!
